LPS-80472 update maven pom.xml with custom registry
Ithildir/liferay-portal pull request #1016
Opened 2018-05-23 22:30 UTC by gamerson

2018-05-23 22:30 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2018-05-23 22:30 UTC, gamerson commented
ci:test:releveant

2018-05-23 22:31 UTC, gamerson commented
ci:test:relevant

2018-05-23 22:31 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-pullrequest(master)/3252/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-1.liferay.com//userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/3252/jenkins-report.html">here</a>.</b></p>

2018-05-23 22:31 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-23.liferay.com/job/test-portal-acceptance-pullrequest(master)/1574/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-23.liferay.com//userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/1574/jenkins-report.html">here</a>.</b></p>

2018-05-23 23:51 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:relevant - 8 out of 8 jobs passed in 1 hour 20 minutes 23 seconds 279 ms</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/60cd5fb7e160b1f8a88c6144cf76a23c9b6729d9">60cd5fb7e160b1f8a88c6144cf76a23c9b6729d9</a></p><h4>Copied in Private Modules Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal-ee/tree/master-private">master-private</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal-ee/commit/421cf6b41ca874678b98a9c05baecd0ae98a0b73">421cf6b41ca874678b98a9c05baecd0ae98a0b73</a></p>8 out of 8 jobs PASSED<details><summary><strong>8 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-23.liferay.com/job/test-portal-acceptance-pullrequest(master)/1574/">test-portal-acceptance-pullrequest(master)</a></li><li><a href="https://test-1-13.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/204898/">test-portal-acceptance-pullrequest-batch(master)/central-requirements-jdk8</a></li><li><a href="https://test-1-22.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/85034/">test-portal-acceptance-pullrequest-batch(master)/functional-smoke-tomcat90-mysql57-jdk8/0</a></li><li><a href="https://test-1-19.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/222874/">test-portal-acceptance-pullrequest-batch(master)/lpkg-controller-jdk8</a></li><li><a href="https://test-1-13.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/204899/">test-portal-acceptance-pullrequest-batch(master)/modules-unit-jdk8</a></li><li><a href="https://test-1-14.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/229512/">test-portal-acceptance-pullrequest-batch(master)/semantic-versioning-jdk8</a></li><li><a href="https://test-1-11.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/225489/">test-portal-acceptance-pullrequest-batch(master)/service-builder-jdk8</a></li><li><a href="https://test-1-8.liferay.com/job/test-portal-acceptance-pullrequest-dist(master)/2104/">test-portal-acceptance-pullrequest-dist(master)/dist-jdk8</a></li></ul></details><h5>For more details click <a href="https://test-1-23.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/1574/jenkins-report.html">here</a>.</h5></details></html>

2018-05-24 00:28 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:releveant - 118 out of 120 jobs passed in 1 hour 57 minutes 40 seconds 320 ms</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/60cd5fb7e160b1f8a88c6144cf76a23c9b6729d9">60cd5fb7e160b1f8a88c6144cf76a23c9b6729d9</a></p><h4>Copied in Private Modules Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal-ee/tree/master-private">master-private</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal-ee/commit/421cf6b41ca874678b98a9c05baecd0ae98a0b73">421cf6b41ca874678b98a9c05baecd0ae98a0b73</a></p>118 out of 120 jobs PASSED<div><h4>2 Failed Jobs:</h4><ul><li><a href="https://test-1-1.liferay.com/job/test-portal-acceptance-pullrequest(master)/3252/"><strike><strong>test-portal-acceptance-pullrequest(master)</strong></strike></a></li><li><a href="https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/239757/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/12</strong></strike></a></li></ul></div><details><summary><strong>118 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/236491/">test-portal-acceptance-pullrequest-batch(master)/bundle-blacklist-restart-jdk8</a></li><li><a href="https://test-1-13.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/204900/">test-portal-acceptance-pullrequest-batch(master)/central-requirements-jdk8</a></li><li><a href="https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/239752/">test-portal-acceptance-pullrequest-batch(master)/compile-jsp-jdk8</a></li><li><a href="https://test-1-14.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/229513/">test-portal-acceptance-pullrequest-batch(master)/empty-temp-dir-jdk8</a></li><li><a href="https://test-1-23.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/86746/">test-portal-acceptance-pullrequest-batch(master)/functional-smoke-jboss71-mysql57-jdk8/0</a></li><li><a href="https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/239753/">test-portal-acceptance-pullrequest-batch(master)/functional-smoke-tcserver40-mysql57-jdk8/0</a></li><li><a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/236492/">test-portal-acceptance-pullrequest-batch(master)/functional-smoke-tomcat90-db2105-jdk8/0</a></li><li><a href="https://test-1-22.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/85035/">test-portal-acceptance-pullrequest-batch(master)/functional-smoke-tomcat90-mariadb100-jdk8/0</a></li><li><a href="https://test-1-21.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/166863/">test-portal-acceptance-pullrequest-batch(master)/functional-smoke-tomcat90-mysql57-jdk8/0</a></li><li><a href="https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/203200/">test-portal-acceptance-pullrequest-batch(master)/functional-smoke-tomcat90-oracle121-jdk8/0</a></li><li><a href="https://test-1-4.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/230060/">test-portal-acceptance-pullrequest-batch(master)/functional-smoke-tomcat90-postgresql94-jdk8/0</a></li><li><a href="https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/211325/">test-portal-acceptance-pullrequest-batch(master)/functional-smoke-tomcat90-sybase160-jdk8/0</a></li><li><a href="https://test-1-21.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/166864/">test-portal-acceptance-pullrequest-batch(master)/functional-smoke-wildfly110-mariadb100-jdk8/0</a></li><li><a href="https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/239754/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/0</a></li><li><a href="https://test-1-4.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/230062/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/1</a></li><li><a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/236494/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/10</a></li><li><a href="https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/203201/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/11</a></li><li><a href="https://test-1-4.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/230065/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/13</a></li><li><a href="https://test-1-21.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/166867/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/14</a></li><li><a href="https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/211326/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/15</a></li><li><a href="https://test-1-15.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/159785/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/16</a></li><li><a href="https://test-1-21.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/166866/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/17</a></li><li><a href="https://test-1-4.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/230064/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/18</a></li><li><a href="https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/239756/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/19</a></li><li><a href="https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/239755/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/2</a></li><li><a href="https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/203203/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/20</a></li><li><a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/236493/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/21</a></li><li><a href="https://test-1-22.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/85036/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/22</a></li><li><a href="https://test-1-12.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/151351/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/23</a></li><li><a href="https://test-1-4.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/230063/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/24</a></li><li><a href="https://test-1-12.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/151350/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/25</a></li><li><a href="https://test-1-14.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/229514/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/26</a></li><li><a href="https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/216007/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/27</a></li><li><a href="https://test-1-21.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/166865/">test-portal-acceptance-pullrequest-batch(master)/functional-to [...]

2018-05-25 16:05 UTC, Ithildir requested changes

2018-05-25 16:05 UTC, Ithildir commented on modules/sdk/project-templates/project-templates/build.gradle
> +	systemProperty "nodejs.npm.ci.sass.binary.site", project.property('nodejs.npm.ci.sass.binary.site')
Can you please use double quotes in Gradle files?

2018-05-25 16:05 UTC, Ithildir commented on modules/sdk/project-templates/project-templates/src/test/java/com/liferay/project/templates/ProjectTemplatesTest.java
> +		File buildFile = _testContains(
Please call it `buildGradleFile`.

2018-05-25 16:05 UTC, Ithildir commented on modules/sdk/project-templates/project-templates/src/test/java/com/liferay/project/templates/ProjectTemplatesTest.java
> +		String executeNpmTaskScript =
I think it would look cleaner with a `StringBuilder`, what do you think?

2018-05-25 16:05 UTC, Ithildir commented on modules/sdk/project-templates/project-templates/src/test/java/com/liferay/project/templates/ProjectTemplatesTest.java
> +		XPathExpression xPathExpression = xPath.compile(
Maybe we can compile the XPath expression in the `@BeforeClass` method.

2018-05-25 16:05 UTC, Ithildir commented on modules/sdk/project-templates/project-templates/src/test/java/com/liferay/project/templates/ProjectTemplatesTest.java
> +		File pomXml = new File(projectDir, "pom.xml");
Please call it `pomXmlFile`.

2018-05-25 16:05 UTC, Ithildir commented on modules/sdk/project-templates/project-templates/src/test/java/com/liferay/project/templates/ProjectTemplatesTest.java
> +		Element configuration = document.createElement("configuration");
Call it `configurationElement`.

2018-05-25 16:05 UTC, Ithildir commented on modules/sdk/project-templates/project-templates/src/test/java/com/liferay/project/templates/ProjectTemplatesTest.java
> +		Node execution = nodeList.item(0);
Call it `executionNode`.

2018-05-25 16:05 UTC, Ithildir commented on modules/sdk/project-templates/project-templates/src/test/java/com/liferay/project/templates/ProjectTemplatesTest.java
> +		Element arguments = document.createElement("arguments");
Call it `argumentsElement`.

2018-05-25 16:05 UTC, Ithildir commented on modules/sdk/project-templates/project-templates/src/test/java/com/liferay/project/templates/ProjectTemplatesTest.java
> +		DOMSource source = new DOMSource(document);
Call it `domSource`.

2018-05-25 16:05 UTC, Ithildir commented on modules/sdk/project-templates/project-templates/src/test/java/com/liferay/project/templates/ProjectTemplatesTest.java
> +		StreamResult result = new StreamResult(pomXml);
Call it `streamResult`.

2018-05-25 16:05 UTC, Ithildir commented on modules/sdk/project-templates/project-templates/src/test/java/com/liferay/project/templates/ProjectTemplatesTest.java
> +		if (Validator.isNotNull(System.getenv("JENKINS_HOME"))) {
Can you please look for `JENKINS_HOME` in this class, and remove the `Assume.assumeFalse` lines? Otherwise, those tests won't even run on CI 😋

2018-05-25 16:05 UTC, Ithildir commented on modules/sdk/project-templates/project-templates/build.gradle
> +	systemProperty "nodejs.npm.ci.sass.binary.site", project.property('nodejs.npm.ci.sass.binary.site')
Is it possible to configure Gradle and Maven to use this custom Sass binary site? Have a look at https://github.com/sass/node-sass#binary-configuration-parameters.

2018-05-25 16:06 UTC, Ithildir requested changes

2018-05-25 16:06 UTC, Ithildir commented on modules/sdk/project-templates/project-templates/src/test/java/com/liferay/project/templates/ProjectTemplatesTest.java
> +						"tasks.withType(ExecuteNpmTask) {registry = '" +
Sure this will work with workspaces? Do we tests NPM projects in workspaces?

2018-05-25 20:19 UTC, gamerson commented
ci:test:relevant

2018-05-25 21:46 UTC, Ithildir commented
Sent to https://github.com/brianchandotcom/liferay-portal/pull/59093.

2018-05-25 21:46 UTC, closed without merging

2018-05-25 22:30 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:relevant - 9 out of 9 jobs passed in 2 hours 5 minutes 27 seconds 145 ms</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/7405cb6b216d9b67f7d0f6e99b8f70b3b1812148">7405cb6b216d9b67f7d0f6e99b8f70b3b1812148</a></p><h4>Copied in Private Modules Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal-ee/tree/master-private">master-private</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal-ee/commit/a5ffe8d14284b7ad9e444acfc9b80f9be959cbd2">a5ffe8d14284b7ad9e444acfc9b80f9be959cbd2</a></p>9 out of 9 jobs PASSED<details><summary><strong>9 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-12.liferay.com/job/test-portal-acceptance-pullrequest(master)/984/">test-portal-acceptance-pullrequest(master)</a></li><li><a href="https://test-1-16.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/224829/">test-portal-acceptance-pullrequest-batch(master)/central-requirements-jdk8</a></li><li><a href="https://test-1-11.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/226001/">test-portal-acceptance-pullrequest-batch(master)/functional-smoke-tomcat90-mysql57-jdk8/0</a></li><li><a href="https://test-1-23.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/87345/">test-portal-acceptance-pullrequest-batch(master)/lpkg-controller-jdk8</a></li><li><a href="https://test-1-16.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/224830/">test-portal-acceptance-pullrequest-batch(master)/modules-integration-mysql57-jdk8</a></li><li><a href="https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/216557/">test-portal-acceptance-pullrequest-batch(master)/modules-unit-jdk8</a></li><li><a href="https://test-1-16.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/224831/">test-portal-acceptance-pullrequest-batch(master)/semantic-versioning-jdk8</a></li><li><a href="https://test-1-23.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/87344/">test-portal-acceptance-pullrequest-batch(master)/service-builder-jdk8</a></li><li><a href="https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest-dist(master)/2367/">test-portal-acceptance-pullrequest-dist(master)/dist-jdk8</a></li></ul></details><h5>For more details click <a href="https://test-1-12.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/984/jenkins-report.html">here</a>.</h5></details></html>