LPS-76201 FAKE GRADLE CACHE
Ithildir/liferay-portal pull request #844
Opened 2017-12-06 17:31 UTC by gamerson

2017-12-06 17:31 UTC, liferay-continuous-integration commented
Pull request test invoked at http://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest(master).

2017-12-06 17:32 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest(master)/1971/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-7.liferay.com//userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/1971/jenkins-report.html">here</a>.</b></p>

2017-12-06 18:51 UTC, liferay-continuous-integration commented
<h1>The pull request tester is still running.</h1><p>Please wait until you get the <i><b>final report</b></i> before running 'ci:retest'.</p><p>See this link to check on the status of your test:</p><ul><li><a href="https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest(master)/1971/">test-portal-acceptance-pullrequest(master)</a></li></ul><p>@gamerson</p><hr /><h1>However, the pull request was closed.</h1><p>The pull request was closed because the following critical batches had failed:</p><ul><li><a href="https://test-1-18.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/200959/">source-format-jdk8</a></li></ul><p>For information as to why we automatically close out certain pull requests see this <a href="https://in.liferay.com/web/global.engineering/wiki/-/wiki/Quality+Assurance+Main/Test+Batch+Automatic+Close+List">article</a>.</p><p auto-close="false"><strong><em>*This pull will no longer automatically close if this comment is available. If you believe this is a mistake please re-open this pull by entering the following command as a comment.</em></strong></p><pre>ci&#58;reopen</pre><hr /><h3>Critical Failure Details:</h3><div><h5><a href="https://test-1-18.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/200959/">test-portal-acceptance-pullrequest-batch(master)/source-format-jdk8</a></h5><div><h6>Job Results:</h6><p>0 Tests Passed.<br/>1 Test Failed.</p></div><ol><li><div><a href="https://test-1-18.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=0,label_exp=!master/200959//consoleText">AXIS_VARIABLE=0,label_exp=!master #200959</a><pre><code>     [exec] :util:source-formatter:classes
     [exec] :util:source-formatter:jar
     [exec] :util:source-formatter:deploy
     [exec] Files of project ':util:source-formatter' deployed to /opt/dev/projects/github/liferay-portal/tools/sdk/dependencies/com.liferay.source.formatter/lib
     [exec] :util:source-formatter:deployDependencies UP-TO-DATE
     [exec] 
     [exec] BUILD SUCCESSFUL
     [exec] 
     [exec] Total time: 11.5 secs
     [exec] Gradle build finished at 2017-12-06 18:48:55.807.
     [exec] 
     [echo] Running com.liferay.source.formatter.jar 1.0.511.

format-source-all:
     [java] Loading file:/opt/dev/projects/github/liferay-portal/portal-impl/classes/system.properties
     [java] SLF4J: Class path contains multiple SLF4J bindings.
     [java] SLF4J: Found binding in [file:/opt/dev/projects/github/liferay-portal/util-slf4j/classes/org/slf4j/impl/StaticLoggerBinder.class]
     [java] SLF4J: Found binding in [jar:file:/opt/dev/projects/github/liferay-portal/lib/development/slf4j-simple.jar!/org/slf4j/impl/StaticLoggerBinder.class]
     [java] SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
     [java] SLF4J: Actual binding is of type [com.liferay.util.sl4fj.LiferayLoggerFactory]
     [java] /opt/dev/projects/github/liferay-portal/modules/sdk/gradle-plugins-soy/build.gradle
     [java] /opt/dev/projects/github/liferay-portal/modules/sdk/project-templates/project-templates-soy-portlet/src/main/resources/archetype-resources/pom.xml
     [java] Exception in thread "main" com.liferay.source.formatter.SourceMismatchException: ./modules/sdk/gradle-plugins-soy/build.gradle expected:&lt;...1", "3.2.1", "3.3"
     [java] }[]&gt; but was:&lt;...1", "3.2.1", "3.3"
     [java] }[
     [java] ]&gt;
     [java] 	at com.liferay.source.formatter.BaseSourceProcessor.processFormattedFile(BaseSourceProcessor.java:407)
     [java] 	at com.liferay.source.formatter.BaseSourceProcessor.format(BaseSourceProcessor.java:281)
     [java] 	at com.liferay.source.formatter.BaseSourceProcessor._format(BaseSourceProcessor.java:533)
     [java] 	at com.liferay.source.formatter.BaseSourceProcessor._performTask(BaseSourceProcessor.java:630)
     [java] 	at com.liferay.source.formatter.BaseSourceProcessor.access$000(BaseSourceProcessor.java:68)
     [java] 	at com.liferay.source.formatter.BaseSourceProcessor$1.call(BaseSourceProcessor.java:114)
     [java] 	at com.liferay.source.formatter.BaseSourceProcessor$1.call(BaseSourceProcessor.java:110)</code></pre></div></li></ol></div>

2017-12-06 20:33 UTC, liferay-continuous-integration commented
<html><h1>Some tests FAILED.</h1><p>Build Time: 3 hours 1 minute 9 seconds 270 ms</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/c36eabd2c04a8ab6774f6750559cb4e3a7a06997">c36eabd2c04a8ab6774f6750559cb4e3a7a06997</a></p><h4>Copied in Private Modules Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal-ee/tree/master-private">master-private</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal-ee/commit/cc4bd3ffea78596b682a79e89464d7fe65aa1d52">cc4bd3ffea78596b682a79e89464d7fe65aa1d52</a></p>110 out of 123 jobs PASSED<div><h4>13 Failed Jobs:</h4><ul><li><a href="https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest(master)/1971/"><strike><strong>test-portal-acceptance-pullrequest(master)</strong></strike></a></li><li><a href="https://test-1-19.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/186481/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/functional-upgrade-jboss70-mysql56-jdk8/2</strong></strike></a></li><li><a href="https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/179962/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/integration-oracle121-jdk8</strong></strike></a></li><li><a href="https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/179963/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/modules-integration-db2105-jdk8</strong></strike></a></li><li><a href="https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/169141/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/modules-integration-hypersonic20-jdk8</strong></strike></a></li><li><a href="https://test-1-19.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/186482/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/modules-integration-mariadb100-jdk8</strong></strike></a></li><li><a href="https://test-1-11.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/187122/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/modules-integration-mysql56-jdk8</strong></strike></a></li><li><a href="https://test-1-1.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/195155/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/modules-integration-oracle121-jdk8</strong></strike></a></li><li><a href="https://test-1-17.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/182594/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/modules-integration-postgresql94-jdk8</strong></strike></a></li><li><a href="https://test-1-8.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/150381/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/modules-integration-sybase160-jdk8</strong></strike></a></li><li><a href="https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/173167/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/modules-unit-jdk8</strong></strike></a></li><li><a href="https://test-1-22.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/47249/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/semantic-versioning-jdk8</strong></strike></a></li><li><a href="https://test-1-18.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/200959/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/source-format-jdk8</strong></strike></a></li></ul></div><details><summary><strong>110 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-23.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/47674/">test-portal-acceptance-pullrequest-batch(master)/bundle-blacklist-restart-jdk8</a></li><li><a href="https://test-1-1.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/195128/">test-portal-acceptance-pullrequest-batch(master)/compile-jsp-jdk8</a></li><li><a href="https://test-1-1.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/195127/">test-portal-acceptance-pullrequest-batch(master)/empty-temp-dir-jdk8</a></li><li><a href="https://test-1-23.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/47677/">test-portal-acceptance-pullrequest-batch(master)/functional-smoke-jboss70-mysql56-jdk8/0</a></li><li><a href="https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/173147/">test-portal-acceptance-pullrequest-batch(master)/functional-smoke-tcserver32-mysql56-jdk8/0</a></li><li><a href="https://test-1-1.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/195130/">test-portal-acceptance-pullrequest-batch(master)/functional-smoke-tomcat80-db2105-jdk8/0</a></li><li><a href="https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/173151/">test-portal-acceptance-pullrequest-batch(master)/functional-smoke-tomcat80-mariadb100-jdk8/0</a></li><li><a href="https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/173152/">test-portal-acceptance-pullrequest-batch(master)/functional-smoke-tomcat80-mysql56-jdk8/0</a></li><li><a href="https://test-1-20.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/198805/">test-portal-acceptance-pullrequest-batch(master)/functional-smoke-tomcat80-oracle121-jdk8/0</a></li><li><a href="https://test-1-1.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/195137/">test-portal-acceptance-pullrequest-batch(master)/functional-smoke-tomcat80-postgresql94-jdk8/0</a></li><li><a href="https://test-1-23.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/47684/">test-portal-acceptance-pullrequest-batch(master)/functional-smoke-tomcat80-sybase160-jdk8/0</a></li><li><a href="https://test-1-1.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/195140/">test-portal-acceptance-pullrequest-batch(master)/functional-smoke-weblogic121-mysql56-jdk8/0</a></li><li><a href="https://test-1-5.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/183574/">test-portal-acceptance-pullrequest-batch(master)/functional-smoke-websphere85-mysql56-jdk8/0</a></li><li><a href="https://test-1-4.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/193087/">test-portal-acceptance-pullrequest-batch(master)/functional-smoke-wildfly100-mariadb100-jdk8/0</a></li><li><a href="https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/173161/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat80-hypersonic20-jdk8/0</a></li><li><a href="https://test-1-4.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/193089/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat80-mysql56-jdk8/0</a></li><li><a href="https://test-1-8.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/150372/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat80-mysql56-jdk8/1</a></li><li><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/175329/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat80-mysql56-jdk8/10</a></li><li><a href="https://test-1-1.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/195145/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat80-mysql56-jdk8/11</a></li><li><a href="https://test-1-14.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/192991/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat80-mysql56-jdk8/12</a></li><li><a href="https://test-1-17.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/182589/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat80-mysql56-jdk8/13</a></li><li><a href="https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest-batch(mast [...]

2017-12-06 20:36 UTC, gamerson commented
ci:reopen

2017-12-06 21:20 UTC, Ithildir requested changes

2017-12-06 21:20 UTC, Ithildir commented on modules/sdk/gradle-plugins-soy/build.gradle
> +}
SF problem.

2017-12-06 21:20 UTC, Ithildir commented on modules/sdk/project-templates/project-templates-soy-portlet/src/main/resources/archetype-resources/pom.xml
> +							<dest>${project.build.outputDirectory}/META-INF/resources</dest>
Can't we sort these?

2017-12-06 21:20 UTC, Ithildir commented on modules/sdk/project-templates/project-templates-soy-portlet/src/main/resources/archetype-resources/pom.xml
> +							<workingPath>${project.build.outputDirectory}/META-INF/resources</workingPath>
Can't we sort these?

2017-12-06 21:20 UTC, Ithildir commented on modules/util/portal-tools-soy-builder/src/main/java/com/liferay/portal/tools/soy/builder/commands/BaseNodeCommand.java
> +		final Runtime runtime = Runtime.getRuntime();
Please don't use `final` if you don't need it.

2017-12-06 21:20 UTC, Ithildir commented on modules/util/portal-tools-soy-builder/src/main/java/com/liferay/portal/tools/soy/builder/commands/BaseNodeCommand.java
> +	private String _workingPath;
Can't we use `File` here?

2017-12-06 21:20 UTC, Ithildir commented on modules/util/portal-tools-soy-builder/src/main/java/com/liferay/portal/tools/soy/builder/commands/BaseNodeCommand.java
> +	private String _nodePath;
Can't we use `File` here?

2017-12-06 21:20 UTC, Ithildir commented on modules/util/portal-tools-soy-builder/src/main/java/com/liferay/portal/tools/soy/builder/commands/BaseNodeCommand.java
> +	private String _modulePath;
Can't we use `File` here?

2017-12-06 21:20 UTC, Ithildir commented on modules/util/portal-tools-soy-builder/src/main/java/com/liferay/portal/tools/soy/builder/commands/TranspileJsCommand.java
> +	public TranspileJsCommand() {
Do we need this constructor?

2017-12-06 21:21 UTC, Ithildir commented
Hi @christopherbryanboyd and @gamerson, can you please address these problems and resend? Thanks!

2017-12-06 21:21 UTC, closed without merging

2017-12-06 21:27 UTC, gamerson commented
will do

2017-12-07 15:30 UTC, christopherbryanboyd commented
Hi @Ithildir , I made these changes you requested and sent you an updated PR here: https://github.com/Ithildir/liferay-portal/pull/845/